#!/bin/ksh
domainHome=$1
packageHome=$2
profileDirPath=${packageHome}/etc/profile.d
packageName=${packageHome##*/}
profilePath=${profileDirPath}/${packageName}.sh
mkdir -p ${profileDirPath}
#echo "#${packageName%%_*}_HOME=${packageHome}" >> ${profilePath}
cd ${packageHome}
git clone https://github.com/mfvalin/rpncomm src
cd src || exit 1
git checkout branch_4.5.16 || exit 1
[[ -z ${AUTO_COMPILE} ]] && exit 0
${packageHome}/bin/install_rpn_comm.sh
