#!/bin/ksh
domainHome=$1
packageHome=$2
profileDirPath=${packageHome}/etc/profile.d
packageName=${packageHome##*/}
profilePath=${profileDirPath}/${packageName}.sh
mkdir -p ${profileDirPath}
#echo "#${packageName%%_*}_HOME=${packageHome}" >> ${profilePath}
[[ -z ${AUTO_COMPILE}${INSTALL_ARCH_LIST} ]] && exit 0
cd ${packageHome}/source || exit 1
${packageHome}/bin/install_makebidon.sh ${INSTALL_ARCH_LIST}
